server:
  port: 8091
  error:
    include-message: always

spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:productDB;DB_CLOSE_DELAY=1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        use_sql_comments: false
        format-sql: false
  sql:
    init:
      platform: h2

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
